In [ ]:
#OR implementation of Neural Net
#Written BY: Rohit Roy Chowdhury
#Mtech DS 2 years

In [40]:
import numpy as np

In [41]:
#creating the datas
x = np.array([0,1])
y = np.array([0,1])
z = np.array([0,1])
a = np.zeros([8,3], dtype='int')
result = np.array([], dtype='int')
count = 0
for i in range(len(x)):
    for j in range(len(y)):
        for k in range(len(z)):
            a[count] = [x[i],y[j],z[k]]
            temp = np.bitwise_or(x[i],y[j])
            result =  np.append(result, np.bitwise_or(temp,z[k]))
            count+=1
            
print(result)
print(a)

[0 1 1 1 1 1 1 1]
[[0 0 0]
 [0 0 1]
 [0 1 0]
 [0 1 1]
 [1 0 0]
 [1 0 1]
 [1 1 0]
 [1 1 1]]


In [42]:
import tensorflow as tf
from tensorflow import keras

In [43]:
from sklearn.model_selection import train_test_split
train_X, test_X, train_y, test_y = train_test_split(a, result)

In [44]:
#first layer
model = tf.keras.Sequential(
[keras.layers.Dense(units = 2, input_shape=[3])])
#second layer
tf.keras.Sequential(
[keras.layers.Dense(units = 1, input_shape=[2])])

In [45]:
model.compile(optimizer="sgd", loss="mse")
model.fit(train_X, train_y, epochs=80)

Epoch 1/80
1/1 [==============================] - 0s 717us/step - loss: 3.0100
Epoch 2/80
1/1 [==============================] - 0s 1ms/step - loss: 2.8896
Epoch 3/80
1/1 [==============================] - 0s 1ms/step - loss: 2.7744
Epoch 4/80
1/1 [==============================] - 0s 922us/step - loss: 2.6642
Epoch 5/80
1/1 [==============================] - 0s 852us/step - loss: 2.5588
Epoch 6/80
1/1 [==============================] - 0s 904us/step - loss: 2.4580
Epoch 7/80
1/1 [==============================] - 0s 895us/step - loss: 2.3615
Epoch 8/80
1/1 [==============================] - 0s 1ms/step - loss: 2.2692
Epoch 9/80
1/1 [==============================] - 0s 1ms/step - loss: 2.1808
Epoch 10/80
1/1 [==============================] - 0s 1ms/step - loss: 2.0963
Epoch 11/80
1/1 [==============================] - 0s 1ms/step - loss: 2.0154
Epoch 12/80
1/1 [==============================] - 0s 1ms/step - loss: 1.9381
Epoch 13/80
1/1 [==============================] - 0s 1ms/step 

In [47]:
results = model.evaluate(test_X, test_y)
print(results)

1/1 [==============================] - 0s 976us/step - loss: 0.6573
0.6573291420936584
